import type { ModuleFlow, ModuleCategory } from './types';

export const CATEGORY_ORDER: ModuleCategory[] = [
  'Operations', 'Governance & Compliance', 'Admin', 'Reports', 'System',
];

export const MODULE_FLOWS: ModuleFlow[] = [
  {
    id: 'filter-operations',
    title: 'Filter Operations',
    category: 'Operations',
    summary: 'Run a filter through its cleaning cycle: start, wash, dry, store, with checklists gating each advance.',
    steps: [
      { label: 'Start Cleaning Cycle', kind: 'action', gate: ['FILTER_OPERATE'],
        description: 'Select a cleaning reason and profile; profile is locked for the whole cycle.' },
      { label: 'Wash In / Wash Out', kind: 'action', gate: ['FILTER_OPERATE'] },
      { label: 'Submit Checklist', kind: 'decision', gate: ['FILTER_OPERATE'],
        description: 'Server blocks advance until the pending checklist is complete.',
        branch: { label: 'Bypass stage (records a deviation)', gate: ['FILTER_BYPASS'] } },
      { label: 'Dry In → set duration → Dry Out', kind: 'action', gate: ['FILTER_OPERATE'],
        description: 'Dryer duration is set and a countdown runs before Dry Out.' },
      { label: 'Storage In / Storage Out', kind: 'action', gate: ['FILTER_OPERATE'] },
      { label: 'Cycle auto-completes at the last stage', kind: 'system', gate: [],
        description: 'When the final STAGE leads to the END node the cycle closes automatically.',
        // Terminate is available throughout as an operator-initiated branch.
      },
      { label: 'Terminate cycle early (with reason)', kind: 'decision', gate: ['FILTER_OPERATE'],
        description: 'Optional off-ramp at any point; requires a reason.' },
    ],
  },
  {
    id: 'filter-list',
    title: 'Filters',
    category: 'Operations',
    summary: 'Build the plant hierarchy (Block / Area / AHU) and manage the filter instances hung off it, including RFID tagging.',
    steps: [
      { label: 'Create Block / Area / AHU', kind: 'action', gate: ['ASSET_CREATE', 'FILTER_CREATE', 'FILTER_HIERARCHY_CREATE'],
        description: 'Hierarchy node created via the generic typed-asset endpoint.' },
      { label: 'Create Filter instance under an AHU', kind: 'action', gate: ['ASSET_CREATE', 'FILTER_CREATE', 'FILTER_HIERARCHY_CREATE'] },
      { label: 'Bulk Upload Filters (CSV / Excel)', kind: 'action', gate: ['ASSET_CREATE', 'FILTER_BULK_UPLOAD'],
        description: 'Alternative to one-by-one create; dynamic columns from the template attributeSchema.' },
      { label: 'Edit Filter / Edit Block / Area / AHU', kind: 'action', gate: ['ASSET_UPDATE', 'FILTER_EDIT', 'FILTER_HIERARCHY_EDIT'] },
      { label: 'Assign / Unassign RFID Tag', kind: 'action', gate: ['ASSET_IDENTIFIER_CREATE', 'ASSET_IDENTIFIER_DELETE', 'FILTER_RFID_MANAGE'],
        description: 'One identifier per filter, backend-enforced.' },
      { label: 'Update Filter Status', kind: 'action', gate: ['FILTER_STATUS_UPDATE'],
        description: 'Lifecycle state change; this route has no broader ASSET_* alternate.' },
      { label: 'Delete Filter / Delete Block / Area / AHU', kind: 'decision', gate: ['ASSET_DELETE', 'FILTER_DELETE', 'FILTER_HIERARCHY_DELETE'] },
    ],
  },
  {
    id: 'filter-retirements',
    title: 'Retirement List',
    category: 'Operations',
    summary: 'Permanently retire a filter out of service; a single-step action with a mandatory reason, viewed on the retired-filter inventory list.',
    steps: [
      { label: 'View Retired Filters', kind: 'system', gate: ['ASSET_READ'] },
      { label: 'Retire Filter (with remarks)', kind: 'action', gate: ['FILTER_RETIRE'],
        description: 'Requires reauth (RETIRE_FILTER); no review/approval step — retirement is immediate and permanent.' },
    ],
  },
  {
    id: 'filter-replacements',
    title: 'Replacement List',
    category: 'Operations',
    summary: 'Upload a replacement schedule, review and approve entries, then replace the physical filter when an entry falls due.',
    steps: [
      { label: 'Upload Replacement Schedule', kind: 'action', gate: ['REPLACEMENT_SCHEDULE_UPLOAD'],
        description: 'All-or-nothing bulk create from an .xlsx template; lands entries as pending review.' },
      { label: 'Review entries', kind: 'decision', gate: ['REPLACEMENT_SCHEDULE_REVIEW'],
        description: 'Reviewer approves (moves to pending-approval) or rejects at this stage.',
        branch: { label: 'Reject at review', gate: ['REPLACEMENT_SCHEDULE_REVIEW'] } },
      { label: 'Approve entries', kind: 'decision', gate: ['REPLACEMENT_SCHEDULE_APPROVE'],
        description: 'Final sign-off; only accepts entries already through review.',
        branch: { label: 'Reject at approval', gate: ['REPLACEMENT_SCHEDULE_APPROVE'] } },
      { label: 'Resubmit a rejected entry', kind: 'decision', gate: ['REPLACEMENT_SCHEDULE_UPLOAD'],
        description: 'Only entries in REJECTED status can be resubmitted; re-enters at review.' },
      { label: 'Replace the physical filter (tablet task)', kind: 'action', gate: ['FILTER_REPLACE'],
        description: 'Executed against a due, approved entry; requires reauth (REPLACE_FILTER); retires the old filter and creates the new one.' },
    ],
  },
  {
    id: 'checklists',
    title: 'Checklists',
    category: 'Operations',
    summary: 'Author and maintain the checklist profiles that gate cleaning-cycle stage advances (question sets, not the submission itself).',
    steps: [
      { label: 'Create Checklist Profile', kind: 'action', gate: ['CHECKLIST_CREATE', 'FCP_CREATE'] },
      { label: 'Add Questions', kind: 'action', gate: ['CHECKLIST_CREATE', 'FCP_CREATE'],
        description: 'Separate endpoint, called after the profile exists.' },
      { label: 'Edit Profile / Edit Questions / Reorder / Enable-Disable', kind: 'action', gate: ['CHECKLIST_EDIT', 'FCP_UPDATE'],
        description: 'Enable/disable is a field on the same edit-profile call — no dedicated toggle route.' },
      { label: 'Delete Question / Delete Profile', kind: 'decision', gate: ['CHECKLIST_DELETE', 'FCP_DELETE'] },
    ],
  },
  {
    id: 'cleaning-profiles',
    title: 'Cleaning Profiles',
    category: 'Operations',
    summary: 'Design the STAGE / CHECKLIST pipeline a cleaning cycle follows, on the visual canvas editor.',
    steps: [
      { label: 'Create Cleaning Profile (build pipeline)', kind: 'action', gate: ['CP_PAGE_CREATE', 'FCP_CREATE'],
        description: 'Stages and connections are authored in the same create call.' },
      { label: 'Edit pipeline (save)', kind: 'action', gate: ['CP_PAGE_EDIT', 'FCP_UPDATE'],
        description: 'Every save auto-versions: archives the outgoing row and inserts version+1 under the same lineage — no separate publish/freeze step.' },
      { label: 'Enable / Disable Profile', kind: 'action', gate: ['CP_PAGE_EDIT', 'FCP_UPDATE'] },
      { label: 'Delete Profile (archive)', kind: 'decision', gate: ['CP_PAGE_DELETE', 'FCP_DELETE'] },
    ],
  },
  {
    id: 'equipment-groups',
    title: 'Equipment Groups',
    category: 'Operations',
    summary: 'Manage AHU equipment groups (the group plus its 3 instrument records) that back the operating-range checks during cleaning.',
    steps: [
      { label: 'Create Equipment Group (+ 3 instruments)', kind: 'action', gate: ['ASSET_CREATE', 'EG_CREATE'],
        description: 'Single composite transaction creating the group and its instrument rows together.' },
      { label: 'Edit Equipment Group / instruments', kind: 'action', gate: ['ASSET_UPDATE', 'EG_EDIT'],
        description: 'Snapshots the outgoing composite into a version sidecar before applying the edit.' },
      { label: 'Enable / Disable Group', kind: 'action', gate: ['ASSET_UPDATE', 'EG_EDIT'] },
      { label: 'Delete Group (deactivate)', kind: 'decision', gate: ['ASSET_DELETE', 'EG_DELETE'] },
    ],
  },
  {
    id: 'pm-schedules',
    title: 'PM Schedules',
    category: 'Operations',
    summary: 'Schedule preventive-maintenance cleaning entries, route them through review and approval, then execute on the due date.',
    steps: [
      { label: 'Create / Upload PM Schedule', kind: 'action', gate: ['PM_CREATE', 'PM_UPLOAD'],
        description: 'Workflow-on uploads always land in PENDING_REVIEW — no SUPER_ADMIN bypass.' },
      { label: 'Review entries', kind: 'decision', gate: ['PM_REVIEW'],
        description: 'Moves PENDING_REVIEW → PENDING_APPROVAL, or rejects. Reviewer role must also match the configured review role (unless SUPER_ADMIN).',
        branch: { label: 'Reject at review', gate: ['PM_REVIEW'] } },
      { label: 'Approve entries', kind: 'decision', gate: ['PM_APPROVE'],
        description: 'Only accepts entries already in PENDING_APPROVAL.',
        branch: { label: 'Reject at approval', gate: ['PM_APPROVE'] } },
      { label: 'Resubmit a rejected entry', kind: 'decision', gate: ['PM_CREATE', 'PM_RESUBMIT'],
        description: 'Only entries in REJECTED status qualify; re-enters at review.' },
      { label: 'Execute PM Task', kind: 'action', gate: ['PM_EXECUTE'],
        description: 'Does NOT require prior approval — execution only checks the entry exists and isn’t already in progress.' },
      { label: 'Acknowledge overdue deviation', kind: 'action', gate: ['PM_EXECUTE'],
        description: 'Reauth is always enforced on this action.' },
    ],
  },
  {
    id: 'my-tasks',
    title: 'My Tasks',
    category: 'Operations',
    summary: 'Read-heavy surface listing PM cleaning tasks currently due for the logged-in operator.',
    steps: [
      { label: 'View due PM tasks', kind: 'system', gate: ['PM_READ'] },
      { label: 'Perform a task (start execution)', kind: 'action', gate: ['PM_EXECUTE'] },
      { label: 'Acknowledge an overdue task', kind: 'action', gate: ['PM_EXECUTE'],
        description: 'Same endpoint as the PM Schedules deviation acknowledge; reauth required.' },
    ],
  },
];
