import type { ModuleFlow, ModuleCategory } from './types';

export const CATEGORY_ORDER: ModuleCategory[] = [
  'Operations', 'Governance & Compliance', 'Admin', 'Reports', 'System',
];

export const MODULE_FLOWS: ModuleFlow[] = [
  {
    id: 'filter-operations',
    title: 'Filter Operations',
    category: 'Operations',
    layout: 'sequence',
    summary: 'Run a filter through its cleaning cycle: start, wash, dry, store, with checklists gating each advance.',
    note: 'The stages below are the full teaching flow. The actual stages a filter goes through depend on the cleaning profile assigned to it — a profile may skip Wash, Dry or Storage stages, so some steps may not appear for a given filter.',
    steps: [
      { label: 'Start Cleaning Cycle', kind: 'action', gate: ['FILTER_OPERATE'],
        description: 'Select a cleaning reason and profile; profile is locked for the whole cycle.' },
      { label: 'Wash In / Wash Out', kind: 'action', gate: ['FILTER_OPERATE'] },
      { label: 'Submit Checklist', kind: 'decision', gate: ['FILTER_OPERATE'],
        description: 'Server blocks advance until the pending checklist is complete.',
        branch: { label: 'Bypass stage (records a deviation)', gate: ['FILTER_BYPASS'] } },
      { label: 'Dry In → set duration → Dry Out', kind: 'action', gate: ['FILTER_OPERATE'],
        description: 'Dryer duration is set and a countdown runs before Dry Out.' },
      { label: 'Storage In / Storage Out', kind: 'action', gate: ['FILTER_OPERATE'] },
      { label: 'Cycle auto-completes at the last stage', kind: 'system', gate: [], access: 'automatic',
        description: 'When the final STAGE leads to the END node the cycle closes automatically.',
        // Terminate is available throughout as an operator-initiated branch.
      },
      { label: 'Terminate cycle early (with reason)', kind: 'decision', gate: ['FILTER_OPERATE'],
        description: 'Optional off-ramp at any point; requires a reason.' },
    ],
  },
  {
    id: 'filter-list',
    title: 'Filters',
    category: 'Operations',
    summary: 'Build the plant hierarchy (Block / Area / AHU) and manage the filter instances hung off it, including RFID tagging.',
    steps: [
      { label: 'Create Block / Area / AHU', kind: 'action', gate: ['ASSET_CREATE', 'FILTER_CREATE', 'FILTER_HIERARCHY_CREATE'],
        description: 'Hierarchy node created via the generic typed-asset endpoint.' },
      { label: 'Create Filter instance under an AHU', kind: 'action', gate: ['ASSET_CREATE', 'FILTER_CREATE', 'FILTER_HIERARCHY_CREATE'] },
      { label: 'Bulk Upload Filters (CSV / Excel)', kind: 'action', gate: ['ASSET_CREATE', 'FILTER_BULK_UPLOAD'],
        description: 'Alternative to one-by-one create; dynamic columns from the template attributeSchema.' },
      { label: 'Edit Filter / Edit Block / Area / AHU', kind: 'action', gate: ['ASSET_UPDATE', 'FILTER_EDIT', 'FILTER_HIERARCHY_EDIT'] },
      { label: 'Assign RFID Tag', kind: 'action', gate: ['ASSET_IDENTIFIER_CREATE', 'FILTER_RFID_MANAGE'],
        description: 'POST /api/assets/identifiers; one identifier per filter, backend-enforced.' },
      { label: 'Unassign RFID Tag', kind: 'action', gate: ['ASSET_IDENTIFIER_DELETE', 'FILTER_RFID_MANAGE'] },
      { label: 'Update Filter Status', kind: 'action', gate: ['FILTER_STATUS_UPDATE'],
        description: 'Lifecycle state change; this route has no broader ASSET_* alternate.' },
      { label: 'Delete Filter / Delete Block / Area / AHU', kind: 'decision', gate: ['ASSET_DELETE', 'FILTER_DELETE', 'FILTER_HIERARCHY_DELETE'] },
    ],
  },
  {
    id: 'filter-retirements',
    title: 'Retirement List',
    category: 'Operations',
    summary: 'Permanently retire a filter out of service; a single-step action with a mandatory reason, viewed on the retired-filter inventory list.',
    steps: [
      { label: 'View Retired Filters', kind: 'system', gate: ['ASSET_READ'] },
      { label: 'Retire Filter (with remarks)', kind: 'action', gate: ['FILTER_RETIRE'],
        description: 'Requires reauth (RETIRE_FILTER); no review/approval step — retirement is immediate and permanent.' },
    ],
  },
  {
    id: 'filter-replacements',
    title: 'Replacement List',
    category: 'Operations',
    layout: 'sequence',
    summary: 'Upload a replacement schedule, review and approve entries, then replace the physical filter when an entry falls due.',
    steps: [
      { label: 'Upload Replacement Schedule', kind: 'action', gate: ['REPLACEMENT_SCHEDULE_UPLOAD'],
        description: 'All-or-nothing bulk create from an .xlsx template; lands entries as pending review.' },
      { label: 'Review entries', kind: 'decision', gate: ['REPLACEMENT_SCHEDULE_REVIEW'],
        description: 'Reviewer approves (moves to pending-approval) or rejects at this stage.',
        branch: { label: 'Reject at review', gate: ['REPLACEMENT_SCHEDULE_REVIEW'] } },
      { label: 'Approve entries', kind: 'decision', gate: ['REPLACEMENT_SCHEDULE_APPROVE'],
        description: 'Final sign-off; only accepts entries already through review.',
        branch: { label: 'Reject at approval', gate: ['REPLACEMENT_SCHEDULE_APPROVE'] } },
      { label: 'Resubmit a rejected entry', kind: 'decision', gate: ['REPLACEMENT_SCHEDULE_UPLOAD'],
        description: 'Only entries in REJECTED status can be resubmitted; re-enters at review.' },
      { label: 'Replace the physical filter (tablet task)', kind: 'action', gate: ['FILTER_REPLACE'],
        description: 'Executed against a due, approved entry; requires reauth (REPLACE_FILTER); retires the old filter and creates the new one.' },
    ],
  },
  {
    id: 'checklists',
    title: 'Checklists',
    category: 'Operations',
    summary: 'Author and maintain the checklist profiles that gate cleaning-cycle stage advances (question sets, not the submission itself).',
    steps: [
      { label: 'Create Checklist Profile', kind: 'action', gate: ['CHECKLIST_CREATE', 'FCP_CREATE'] },
      { label: 'Add Questions', kind: 'action', gate: ['CHECKLIST_CREATE', 'FCP_CREATE'],
        description: 'Separate endpoint, called after the profile exists.' },
      { label: 'Edit Profile / Edit Questions / Reorder / Enable-Disable', kind: 'action', gate: ['CHECKLIST_EDIT', 'FCP_UPDATE'],
        description: 'Enable/disable is a field on the same edit-profile call — no dedicated toggle route.' },
      { label: 'Delete Question / Delete Profile', kind: 'decision', gate: ['CHECKLIST_DELETE', 'FCP_DELETE'] },
    ],
  },
  {
    id: 'cleaning-profiles',
    title: 'Cleaning Profiles',
    category: 'Operations',
    summary: 'Design the STAGE / CHECKLIST pipeline a cleaning cycle follows, on the visual canvas editor.',
    steps: [
      { label: 'Create Cleaning Profile (build pipeline)', kind: 'action', gate: ['CP_PAGE_CREATE', 'FCP_CREATE'],
        description: 'Stages and connections are authored in the same create call.' },
      { label: 'Edit pipeline (save)', kind: 'action', gate: ['CP_PAGE_EDIT', 'FCP_UPDATE'],
        description: 'Every save auto-versions: archives the outgoing row and inserts version+1 under the same lineage — no separate publish/freeze step.' },
      { label: 'Enable / Disable Profile', kind: 'action', gate: ['CP_PAGE_EDIT', 'FCP_UPDATE'] },
      { label: 'Delete Profile (archive)', kind: 'decision', gate: ['CP_PAGE_DELETE', 'FCP_DELETE'] },
    ],
  },
  {
    id: 'equipment-groups',
    title: 'Equipment Groups',
    category: 'Operations',
    summary: 'Manage AHU equipment groups (the group plus its 3 instrument records) that back the operating-range checks during cleaning.',
    steps: [
      { label: 'Create Equipment Group (+ 3 instruments)', kind: 'action', gate: ['ASSET_CREATE', 'EG_CREATE'],
        description: 'Single composite transaction creating the group and its instrument rows together.' },
      { label: 'Edit Equipment Group / instruments', kind: 'action', gate: ['ASSET_UPDATE', 'EG_EDIT'],
        description: 'Snapshots the outgoing composite into a version sidecar before applying the edit.' },
      { label: 'Enable / Disable Group', kind: 'action', gate: ['ASSET_UPDATE', 'EG_EDIT'] },
      { label: 'Delete Group (deactivate)', kind: 'decision', gate: ['ASSET_DELETE', 'EG_DELETE'] },
    ],
  },
  {
    id: 'pm-schedules',
    title: 'PM Schedules',
    category: 'Operations',
    layout: 'sequence',
    summary: 'Schedule preventive-maintenance cleaning entries, route them through review and approval, then execute on the due date.',
    steps: [
      { label: 'Create / Upload PM Schedule', kind: 'action', gate: ['PM_CREATE', 'PM_UPLOAD'],
        description: 'Workflow-on uploads always land in PENDING_REVIEW — no SUPER_ADMIN bypass.' },
      { label: 'Review entries', kind: 'decision', gate: ['PM_REVIEW'],
        description: 'Moves PENDING_REVIEW → PENDING_APPROVAL, or rejects. Reviewer role must also match the configured review role (unless SUPER_ADMIN).',
        branch: { label: 'Reject at review', gate: ['PM_REVIEW'] } },
      { label: 'Approve entries', kind: 'decision', gate: ['PM_APPROVE'],
        description: 'Only accepts entries already in PENDING_APPROVAL.',
        branch: { label: 'Reject at approval', gate: ['PM_APPROVE'] } },
      { label: 'Resubmit a rejected entry', kind: 'decision', gate: ['PM_CREATE', 'PM_RESUBMIT'],
        description: 'Only entries in REJECTED status qualify; re-enters at review.' },
      { label: 'Execute PM Task', kind: 'action', gate: ['PM_EXECUTE'],
        description: 'Does NOT require prior approval — execution only checks the entry exists and isn’t already in progress.' },
      { label: 'Acknowledge overdue deviation', kind: 'action', gate: ['PM_EXECUTE'],
        description: 'Reauth is always enforced on this action.' },
    ],
  },
  {
    id: 'my-tasks',
    title: 'My Tasks',
    category: 'Operations',
    summary: 'Read-heavy surface listing PM cleaning tasks currently due for the logged-in operator.',
    steps: [
      { label: 'View due PM tasks', kind: 'system', gate: ['PM_READ'] },
      { label: 'Perform a task (start execution)', kind: 'action', gate: ['PM_EXECUTE'] },
      { label: 'Acknowledge an overdue task', kind: 'action', gate: ['PM_EXECUTE'],
        description: 'Same endpoint as the PM Schedules deviation acknowledge; reauth required.' },
    ],
  },
  {
    id: 'approvals',
    title: 'Approvals (Block Change)',
    category: 'Governance & Compliance',
    layout: 'sequence',
    summary: 'Request to move a filter to a different Block, then route the request through a role-gated approve/reject decision.',
    steps: [
      { label: 'Submit Block Change Request', kind: 'action', gate: ['BLOCK_CHANGE_REQUEST'],
        description: 'Requester proposes moving a filter from its current Block to a target Block, with an optional reason.' },
      { label: 'View pending / my requests', kind: 'system', gate: ['BLOCK_CHANGE_REQUEST', 'BLOCK_CHANGE_APPROVE'],
        description: 'List endpoint accepts either the requester or the approver permission (requireAnyPermission) so both sides can see the queue.' },
      { label: 'Approve request', kind: 'decision', gate: ['BLOCK_CHANGE_APPROVE'],
        description: 'Reauth always enforced (APPROVE_BLOCK_CHANGE). If a specific approver role is configured (block-change-approval.approvalRole), only that role — or SUPER_ADMIN — may act, on top of the permission gate.',
        branch: { label: 'Reject request', gate: ['BLOCK_CHANGE_APPROVE'] } },
    ],
  },
  {
    id: 'stage-approvals',
    title: 'Stage Approvals',
    category: 'Governance & Compliance',
    layout: 'sequence',
    summary: 'Approver-side release gate for cleaning stages configured with an interlock: an operator is held at the stage until an approver signs off.',
    steps: [
      { label: 'View my approval queue', kind: 'system', gate: ['STAGE_APPROVAL_VIEW'],
        description: 'Same gate also covers the broader list (?status=) and the full record with its frozen details snapshot.' },
      { label: 'Approve stage (release operator)', kind: 'decision', gate: ['STAGE_APPROVAL_DECIDE'],
        description: 'Reauth is always enforced (APPROVE_CLEANING_STAGE) — the password re-entry doubles as the digital signature.',
        branch: { label: 'Reject stage (send filter back; remarks mandatory)', gate: ['STAGE_APPROVAL_DECIDE'] } },
    ],
  },
  {
    id: 'report-reviews',
    title: 'Report Reviews',
    category: 'Governance & Compliance',
    layout: 'sequence',
    summary: 'Ad-hoc three-stage sign-off for a generated report snapshot: submit, review, then final approve.',
    steps: [
      { label: 'Submit report for review', kind: 'action', gate: ['REPORT_REVIEW_SUBMIT'],
        description: 'Snapshots the report data and assigns it to a user or role at the review stage.' },
      { label: 'View my queue / report list / detail', kind: 'system', gate: ['REPORT_REVIEW_SUBMIT', 'REPORT_REVIEW', 'REPORT_APPROVE'],
        description: 'Shared by submitter, reviewer, and approver (requireAnyPermission).' },
      { label: 'Review report', kind: 'decision', gate: ['REPORT_REVIEW'],
        description: 'Reauth always enforced (REVIEW_REPORT). Approving here only advances it to the approval stage — not a final sign-off.',
        branch: { label: 'Reject at review', gate: ['REPORT_REVIEW'] } },
      { label: 'Approve report', kind: 'decision', gate: ['REPORT_APPROVE'],
        description: 'Reauth always enforced (APPROVE_REPORT); this is the final sign-off, moving the report to APPROVED.',
        branch: { label: 'Reject at approval', gate: ['REPORT_APPROVE'] } },
    ],
  },
  {
    id: 'deviations',
    title: 'Deviations',
    category: 'Governance & Compliance',
    summary: 'Read-only audit trail of overdue AHU preventive-maintenance cleaning tasks; deviation records open and close automatically.',
    steps: [
      { label: 'Deviation opens / closes automatically', kind: 'system', gate: [], access: 'automatic',
        description: 'The idempotent sweep runs on a daily cron (08:30): opens a deviation once a scheduled AHU cleaning task passes its PM tolerance window, and closes it once the filters are cleaned. A manual-trigger endpoint (POST /api/pm-schedules/deviations/sweep, gate PM_UPDATE) exists but is not wired to any current UI.' },
      { label: 'View Deviations', kind: 'system', gate: ['PM_READ'] },
      { label: 'Export report (PDF / Excel)', kind: 'action', gate: ['PM_READ'],
        description: 'Frontend-only export of the currently loaded/filtered list — no dedicated backend export route, so it is gated on the same PM_READ as the view.' },
    ],
  },
  {
    id: 'audit',
    title: 'Audit Trail',
    category: 'Governance & Compliance',
    summary: '21 CFR Part 11 hash-chained record of every audited action; read/export for most roles, with tamper-safe redaction and a loud, chain-breaking physical delete reserved for elevated access.',
    steps: [
      { label: 'View audit trail (list + record detail)', kind: 'system', gate: ['AUDIT_READ'],
        description: 'A SUPER_ADMIN viewer additionally sees SUPER_ADMIN-authored rows; every other role never sees them, on both the list and detail endpoints.' },
      { label: 'Export audit report (PDF / Excel)', kind: 'action', gate: ['AUDIT_EXPORT'],
        description: 'Frontend-only export of the currently loaded query results; no dedicated backend export route.' },
      { label: 'Redact record (single or bulk)', kind: 'decision', gate: [], gateRoles: ['SUPER_ADMIN'],
        description: 'SUPER_ADMIN-only (requireSuperAdmin() — no discrete permission constant gates it). Reauth always enforced (REDACT_AUDIT_RECORD / BULK_REDACT_AUDIT_RECORDS). NULLs the before/after payload but preserves the checksum and chain link — the 21 CFR §11.10(e)-compliant path.' },
      { label: 'Permanently delete record (single or bulk)', kind: 'decision', gate: ['AUDIT_DELETE'],
        description: 'Reauth always enforced (DELETE_AUDIT_RECORD / BULK_DELETE_AUDIT_RECORDS); a meta-audit row records who deleted what and why before the target row is destroyed. WARNING: physically breaks the tamper-evident hash chain — verify-chain will report the downstream chain invalid, permanently. Redact is the recommended alternative.' },
      { label: 'Verify hash chain integrity', kind: 'system', gate: [], gateRoles: ['SUPER_ADMIN'],
        description: 'SUPER_ADMIN-only (requireSuperAdmin()). Walks the chain in chain_position order and reports any checksum mismatch, chain-link mismatch, or position gap.' },
    ],
  },
  {
    id: 'version-history',
    title: 'Version History',
    category: 'Governance & Compliance',
    summary: 'Read-only lineage browser: every edit to a Cleaning Profile, Checklist Profile, Filter Profile, or Equipment Group archives the outgoing row, and this page inspects any prior frozen version.',
    steps: [
      { label: 'View version list + frozen snapshot at version N', kind: 'system', gate: ['VERSION_HISTORY_VIEW'],
        description: 'Each entity’s /:id/versions and /:id/versions/:n endpoints accept VERSION_HISTORY_VIEW as an OR-alternate alongside that entity’s own read/toggle permission (FCP_READ + CP_TOGGLE for cleaning profiles, FCP_READ + CHECKLIST_TOGGLE for checklists, FP_READ for filter profiles, ASSET_READ + EG_VIEW for equipment groups) — VERSION_HISTORY_VIEW is what lets a role browse history without also holding the entity’s live-page permission.' },
    ],
  },
  {
    id: 'users',
    title: 'Users',
    category: 'Admin',
    summary: 'Create and administer user accounts: edit profile/role, enable/disable, unlock locked accounts, and reset passwords; account deletion is reserved for SUPER_ADMIN.',
    steps: [
      { label: 'View user list / detail / stats', kind: 'system', gate: ['USER_READ'] },
      { label: 'Create User', kind: 'action', gate: ['USER_CREATE'],
        description: 'Reauth always enforced (CREATE_USER).' },
      { label: 'Edit User (profile / role / status)', kind: 'action', gate: ['USER_UPDATE'],
        description: 'Reauth always enforced (UPDATE_USER).' },
      { label: 'Enable / Disable User', kind: 'action', gate: ['USER_ENABLE_DISABLE'],
        description: 'Disable also terminates the account’s active sessions. Reauth enforced (ENABLE_USER / DISABLE_USER).' },
      { label: 'Unlock User (locked account, set temp password)', kind: 'action', gate: ['USER_UNLOCK'],
        description: 'Reauth always enforced (UNLOCK_USER); user must change password on next login.' },
      { label: 'Reset Password (admin-initiated)', kind: 'action', gate: ['USER_RESET_PASSWORD'],
        description: 'Reauth always enforced (RESET_PASSWORD). Same permission also gates listing and processing (approve/reject) self-service password-reset requests.' },
      { label: 'Process a password-reset request (approve / reject)', kind: 'decision', gate: ['USER_RESET_PASSWORD'],
        description: 'Reauth always enforced (PROCESS_RESET_REQUEST).' },
      { label: 'Delete User (single or bulk)', kind: 'decision', gate: [], gateRoles: ['SUPER_ADMIN'],
        description: 'SUPER_ADMIN-only (requireSuperAdmin() — no discrete permission constant gates it; the USER_DELETE constant exists but is no longer used as a route gate). Reauth always enforced (DELETE_USER / BULK_DELETE_USERS). Permanently removes the user and related data.' },
    ],
  },
  {
    id: 'admin-requests',
    title: 'Admin Requests',
    category: 'Admin',
    layout: 'sequence',
    summary: 'Public self-service intake for create-user / modify-user / unlock / forgot-password requests, routed to an admin for approval or rejection.',
    steps: [
      { label: 'Submit a request (public, unauthenticated)', kind: 'action', gate: [], access: 'public',
        description: 'No auth required (skipAuth route, rate-limited by IP); a guest picks CREATE_USER / MODIFY_USER / UNLOCK / FORGOT_PASSWORD and supplies their name + employee ID. A companion public lookup endpoint confirms an employee ID exists and returns only its full name and role (never email, department or status; a SUPER_ADMIN stays masked). Modify User changes the role only.' },
      { label: 'View pending requests / count', kind: 'system', gate: ['ADMIN_REQUEST_APPROVE', 'ADMIN_REQUEST_REJECT'],
        description: 'List and pending-count endpoints accept either permission (requireAnyPermission).' },
      { label: 'Approve request', kind: 'decision', gate: ['ADMIN_REQUEST_APPROVE'],
        description: 'Single process endpoint is body-aware: the action value in the request body selects which permission is checked before the handler runs. Reauth always enforced (APPROVE_ADMIN_REQUEST) regardless of approve/reject. Approving CREATE_USER / UNLOCK / FORGOT_PASSWORD generates the account or temporary password.',
        branch: { label: 'Reject request', gate: ['ADMIN_REQUEST_REJECT'] } },
    ],
  },
  {
    id: 'configuration',
    title: 'Configuration',
    category: 'Admin',
    summary: 'Central settings surface for the platform: view and edit the 35 auto-discovered config modules (password policy, session, branding, and more), plus dedicated role/user permission management.',
    steps: [
      { label: 'View a configuration page', kind: 'system', gate: ['CONFIG_READ'],
        description: 'Covers the hardcoded password-policy / login-security / session / datetime / pagination endpoints. Most of the other auto-discovered config defs carry their own read/write permission pair from the def registry rather than CONFIG_READ/CONFIG_UPDATE directly, and a small subset (e.g. offline-cache settings) are SUPER_ADMIN-only (requireSuperAdmin()) instead of permission-gated.' },
      { label: 'Update configuration values', kind: 'action', gate: ['CONFIG_UPDATE'],
        description: 'Sensitive configs (password policy, login security, session, datetime) always require reauth, using either a dynamic action-reauth mapping or a hardcoded current-password check.' },
      { label: 'Manage role permissions / sidebar / home widgets', kind: 'action', gate: ['ROLE_MANAGE'],
        description: 'Sub-flow: PUT /api/config/roles/:role and PUT /api/config/users/:userId (per-user override). Split off CONFIG_UPDATE 2026-06-30 as role/permission administration rather than generic config. Reauth always enforced (UPDATE_ROLE_CONFIG / UPDATE_USER_CONFIG). Viewing role/user configs stays under CONFIG_READ.' },
    ],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    category: 'Admin',
    summary: 'Per-user notification inbox — list, mark read/unread, and (where granted) delete; largely a read/self-service surface with no discrete view permission.',
    steps: [
      { label: 'View notifications / unread count, mark read or unread', kind: 'system', gate: [], access: 'authenticated',
        description: 'No permission check on any of these routes — results are inherently scoped to the caller (SUPER_ADMIN sees all, ADMIN sees non-SUPER_ADMIN, others see only their own). The NOTIFICATION_VIEW permission constant exists but is not enforced by any route.' },
      { label: 'Delete notification (single or bulk)', kind: 'decision', gate: ['NOTIFICATION_DELETE'],
        description: 'Made a real grantable permission 2026-07-01 (previously SUPER_ADMIN-only); SUPER_ADMIN still bypasses. Reauth always enforced (DELETE_NOTIFICATION / BULK_DELETE_NOTIFICATIONS).' },
    ],
  },
  {
    id: 'cleaning-cycles',
    title: 'Filter Cleaning Record',
    category: 'Reports',
    summary: 'Read-only unified report of cleaning cycles and manual filter-status changes, with a per-cycle timeline drill-down and PDF/Excel export.',
    steps: [
      { label: 'View Filter Cleaning Record (list, manual-updates tab, per-cycle timeline)', kind: 'system', gate: ['CYCLE_READ'],
        description: 'GET /api/filters/cleaning-record merges cleaning cycles + manual status updates into one date-sorted, hierarchy/status/reason-filterable list; GET /api/filters/cycles/:id (row drill-down) and GET /api/filters/manual-status-changes (the Manual Status Updates tab) share the same CYCLE_READ gate — all three merged into one step.' },
      { label: 'Export Cleaning Record (PDF / Excel)', kind: 'action', gate: ['REPORT_EXPORT', 'REPORT_GENERATE'],
        description: 'Client-side export of the currently loaded/filtered rows — no backend export route. The button is gated on useCan(\'cleaning_record.export\'), which ORs REPORT_EXPORT/REPORT_GENERATE (SUPER_ADMIN bypasses); a "Send for Review" affordance also exists on this page but is globally disabled in code (SEND_FOR_REVIEW_ENABLED = false) and renders nothing.' },
    ],
  },
  {
    id: 'filter-lifecycle-report',
    title: 'Filter Lifecycle Report',
    category: 'Reports',
    summary: 'Read-only per-filter cleaning lifecycle report — every cycle a filter has been through, cycle by cycle — with retirement/replacement context and PDF/Excel export.',
    steps: [
      { label: 'View Filter Lifecycle Report (per-filter cycle history + expand detail)', kind: 'system', gate: ['CYCLE_READ'],
        description: 'GET /api/filters/cycles (list), GET /api/filters/cycles/:id (expand-row detail), and GET /api/filters/manual-status-changes all share CYCLE_READ — merged into one step.' },
      { label: 'Load retirement / replacement context', kind: 'system', gate: ['ASSET_READ'],
        description: 'GET /api/filters/retirements and GET /api/filters/replacements supply the retired/replaced badges shown alongside a filter\'s cycle history; both gate on ASSET_READ (filter-operations/routes.ts), a different permission than the page\'s core CYCLE_READ — kept as a separate step rather than folded into an OR gate on the view step.' },
      { label: 'Export Filter Lifecycle Report (PDF / Excel)', kind: 'action', gate: ['REPORT_EXPORT', 'REPORT_GENERATE'],
        description: 'Client-side export, no backend export route. Gated on useCan(\'lifecycle.export\'), which ORs REPORT_EXPORT/REPORT_GENERATE (SUPER_ADMIN bypasses).' },
    ],
  },
  {
    id: 'rfid-track-record',
    title: 'RFID Track Record',
    category: 'Reports',
    summary: 'Read-only report of the complete RFID tag assign/remove lifecycle history across all filters, with PDF/Excel export. (RFID assignment itself is done from the Filters page, not here.)',
    steps: [
      { label: 'View RFID Track Record', kind: 'system', gate: ['ASSET_VIEW', 'FILTER_RFID_MANAGE'],
        description: 'GET /api/assets/identifiers/track-record — requireAnyPermission(\'ASSET_VIEW\', \'FILTER_RFID_MANAGE\'). Full assign/remove history with filter/AHU/user/reason columns.' },
      { label: 'Export RFID Track Record (PDF / Excel)', kind: 'action', gate: ['ASSET_VIEW', 'FILTER_RFID_MANAGE'],
        description: 'Client-side export, no backend export route. Gated on useCan(\'rfid_track.export\'), whose permission-tree node carries the SAME gate as the view (a cosmetic/ungated node — no dedicated export permission exists, so it inherits the page\'s read gate; SUPER_ADMIN bypasses).' },
    ],
  },
  {
    id: 'quality-notifications',
    title: 'Quality Notifications',
    category: 'Reports',
    summary: 'Read-only report of Quality Notification Numbers (QNN) minted by the PM Schedule review/approval workflow (upload/review/approve/reject/resubmit/edit), with PDF/Excel export. Visibility is config-gated per role, not permission-mapped — this page has no PERMISSION_TREE node at all.',
    steps: [
      { label: 'View Quality Notifications (QNN) list', kind: 'system', gate: [], access: 'configured',
        description: 'GET /api/pm-schedules/qnn/visible and GET /api/pm-schedules/qnn carry no requirePermission/requireAnyPermission preHandler at all — both call canSeeQnn(req.user.role), which checks the role against the qnn-notifications.visibleRoles list in systemConfig (SUPER_ADMIN always allowed); the list route 403s server-side if the role isn\'t listed. No PERMISSIONS constant is involved, so gate is [] rather than a role-config toggle.' },
      { label: 'Export QNN report (PDF / Excel)', kind: 'action', gate: [], access: 'configured',
        description: 'Client-side export of the currently loaded rows; the export menu on this page has no useCan() check at all — once the page itself is visible (config-gated, see above) export is unconditionally available.' },
    ],
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    category: 'System',
    summary: 'Read-only landing page shown right after login, pulling stats from several existing modules; a separate widget-dashboard CRUD backend exists but is not wired into any frontend page.',
    steps: [
      { label: 'View Dashboard (landing page)', kind: 'system', gate: [], access: 'authenticated',
        description: 'Default route at "/", not wrapped in <RequireRole> — every authenticated user sees it. Pulls /api/users/stats (admin only), /api/audit?limit=1, /api/notifications?limit=1, /api/filters/dashboard-stats, /api/config/dashboard-cards/current, and /api/assets/instances; none of these belong to the /api/dashboards module.' },
      { label: 'Widget-dashboard CRUD (parked backend feature)', kind: 'system', gate: ['DASHBOARD_VIEW'],
        description: 'The /api/dashboards module (list/get gate DASHBOARD_VIEW; create gates DASHBOARD_CREATE; update/delete/widgets/layout gate DASHBOARD_MANAGE; assign/unassign gate DASHBOARD_ASSIGN) is feature-complete but parked since 2026-04-30 — no frontend page calls it. The dashboard.* permission-tree toggles are grantable but have no visible effect until a drag-drop widget canvas page is built.' },
    ],
  },
  {
    id: 'system-health',
    title: 'System Health',
    category: 'System',
    summary: 'Read-only diagnostics page: OS, memory, CPU, disk, process, API-traffic, and database metrics for the local server.',
    steps: [
      { label: 'View System Health metrics', kind: 'system', gate: [], gateRoles: ['SUPER_ADMIN', 'ADMIN'],
        description: 'GET /api/system-health uses requireRole(\'SUPER_ADMIN\', \'ADMIN\') rather than a permission constant — ADMIN or SUPER_ADMIN only, no discrete permission gates it. The permission-tree\'s system_health.view node lists gateRoles: [\'ADMIN\'] only because SUPER_ADMIN is an implicit frontend bypass there; this Module Guide states both roles explicitly since it must reflect the real backend requireRole() list.' },
    ],
  },
  {
    id: 'debug-traces',
    title: 'Debug Traces',
    category: 'System',
    summary: 'Read-only operations log repointed onto audit_trail: every audited action renders as a single-stage SUCCESS trace, plus two vestigial tracing toggles kept for UI compatibility.',
    steps: [
      { label: 'View traces (list, stats, detail, tracing-flag read)', kind: 'system', gate: ['READ_DEBUG_TRACE'],
        description: 'GET /, GET /stats, GET /:id, and GET /operation-trace all gate on READ_DEBUG_TRACE. Since audit_trail only records successes, finalStatus is always SUCCESS, there are no error codes, and durations are always 0.' },
      { label: 'Toggle tracing flags (vestigial)', kind: 'action', gate: ['MANAGE_DEBUG_TRACE'],
        description: 'PUT /operation-trace (global) and PUT /entity/:id/toggle (per-entity) are no-ops kept only so the UI can persist a flag without erroring — the underlying pipeline tracer was retired with the ingestion/TSDB removal.' },
    ],
  },
];
