import { gzipSync, gunzipSync } from 'node:zlib';
import AdmZip from 'adm-zip';

import { auditLog } from '../../lib/audit.js';
import type { RequestContext } from '../../types/context.js';
import {
  fetchAllTablesRaw,
  fetchAllTablesPrisma,
  restoreFromBackup,
} from './backup.repository.js';
import {
  computeBackupChecksum,
  DB_TABLES,
  escapeSqlValue,
  generateCsv,
  type BackupData,
} from './backup.helpers.js';

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/** Generate a date string suitable for filenames (e.g. "2026-02-21_10-30-00"). */
function dateStamp(): string {
  return new Date()
    .toISOString()
    .replace(/T/, '_')
    .replace(/:/g, '-')
    .replace(/\..+/, '');
}

/**
 * Parse a raw backup file buffer into a BackupData object.
 * Handles gzip detection (.bak) and JSON parsing.
 * Throws with structured { code, message } on failure.
 */
/**
 * Parse a CSV string into an array of objects using the header row as keys.
 */
function parseCsvContent(csvString: string): Record<string, any>[] {
  const lines = csvString.split('\n').filter(l => l.trim());
  if (lines.length < 2) return [];

  // Parse header
  const headers = parseCsvLine(lines[0]);
  const rows: Record<string, any>[] = [];

  for (let i = 1; i < lines.length; i++) {
    const values = parseCsvLine(lines[i]);
    const row: Record<string, any> = {};
    for (let j = 0; j < headers.length; j++) {
      let val: any = values[j] ?? '';
      // Try to parse JSON objects/arrays
      if ((val.startsWith('{') && val.endsWith('}')) || (val.startsWith('[') && val.endsWith(']'))) {
        try { val = JSON.parse(val); } catch {}
      }
      // Convert "true"/"false" to boolean
      else if (val === 'true') val = true;
      else if (val === 'false') val = false;
      // Convert numeric strings
      else if (val !== '' && !isNaN(Number(val)) && !val.includes('-') && val.length < 15) val = Number(val);
      // Convert empty to null
      else if (val === '') val = null;
      row[headers[j]] = val;
    }
    rows.push(row);
  }
  return rows;
}

/** Parse a single CSV line respecting quoted fields */
function parseCsvLine(line: string): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"' && line[i + 1] === '"') { current += '"'; i++; }
      else if (ch === '"') { inQuotes = false; }
      else { current += ch; }
    } else {
      if (ch === '"') { inQuotes = true; }
      else if (ch === ',') { result.push(current); current = ''; }
      else { current += ch; }
    }
  }
  result.push(current);
  return result;
}

/**
 * Parse SQL backup into BackupData by extracting INSERT statements.
 */
function parseSqlBackup(sqlContent: string): BackupData {
  const data: Record<string, any[]> = {};

  // Match INSERT INTO "tablename" (columns) VALUES (values);
  const insertRegex = /INSERT INTO "([^"]+)"\s*\(([^)]+)\)\s*VALUES\s*\((.+?)\);/g;
  let match;

  while ((match = insertRegex.exec(sqlContent)) !== null) {
    const table = match[1];
    const columns = match[2].split(',').map(c => c.trim().replace(/"/g, ''));
    const valuesStr = match[3];

    // Parse values (handle quoted strings, NULL, booleans, numbers, jsonb)
    const values = parseSqlValues(valuesStr);

    if (!data[table]) data[table] = [];
    const row: Record<string, any> = {};
    for (let i = 0; i < columns.length; i++) {
      row[columns[i]] = values[i] ?? null;
    }
    data[table].push(row);
  }

  // Extract metadata from SQL comments
  let generatedBy = 'unknown';
  let timestamp = new Date().toISOString();
  const byMatch = sqlContent.match(/-- Generated By: (.+)/);
  if (byMatch) generatedBy = byMatch[1].trim();
  const tsMatch = sqlContent.match(/-- Generated: (.+)/);
  if (tsMatch) timestamp = tsMatch[1].trim();

  return {
    metadata: {
      version: '1.0.0',
      timestamp,
      generatedBy,
      tableCount: Object.keys(data).length,
      checksum: computeBackupChecksum(convertDbKeysToPrisma(data)),
      format: 'sql',
    },
    data: convertDbKeysToPrisma(data),
  };
}

/** Parse SQL VALUES string into JS values */
function parseSqlValues(valuesStr: string): any[] {
  const result: any[] = [];
  let current = '';
  let inString = false;
  let depth = 0;

  for (let i = 0; i < valuesStr.length; i++) {
    const ch = valuesStr[i];
    if (inString) {
      if (ch === "'" && valuesStr[i + 1] === "'") { current += "'"; i++; }
      else if (ch === "'") {
        inString = false;
        // Check for ::jsonb cast
        if (valuesStr.substring(i + 1, i + 8) === '::jsonb') {
          i += 7;
          try { result.push(JSON.parse(current)); } catch { result.push(current); }
        } else {
          result.push(current);
        }
        current = '';
      }
      else { current += ch; }
    } else {
      if (ch === "'") { inString = true; current = ''; }
      else if (ch === ',' && depth === 0) {
        const trimmed = current.trim();
        if (trimmed === 'NULL') result.push(null);
        else if (trimmed === 'TRUE') result.push(true);
        else if (trimmed === 'FALSE') result.push(false);
        else if (trimmed && !isNaN(Number(trimmed))) result.push(Number(trimmed));
        current = '';
      }
      else { current += ch; }
    }
  }
  // Handle last value
  if (!inString) {
    const trimmed = current.trim();
    if (trimmed === 'NULL') result.push(null);
    else if (trimmed === 'TRUE') result.push(true);
    else if (trimmed === 'FALSE') result.push(false);
    else if (trimmed && !isNaN(Number(trimmed))) result.push(Number(trimmed));
    else if (trimmed) result.push(trimmed);
  }

  return result;
}


/** Convert snake_case DB column names to camelCase Prisma field names in row data */
function convertDbColumnsToPrisma(data: Record<string, any[]>): Record<string, any[]> {
  // Map of DB column name -> Prisma field name (only for columns that differ)
  const COLUMN_MAP: Record<string, string> = {
    display_name: 'displayName',
    hierarchy_level: 'hierarchyLevel',
    is_system: 'isSystem',
    is_active: 'isActive',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
    created_by: 'createdBy',
    updated_by: 'updatedBy',
    full_name: 'fullName',
    password_hash: 'passwordHash',
    photo_url: 'photoUrl',
    failed_login_attempts: 'failedLoginAttempts',
    locked_at: 'lockedAt',
    lockout_until: 'lockoutUntil',
    password_changed_at: 'passwordChangedAt',
    password_expires_at: 'passwordExpiresAt',
    force_password_change: 'forcePasswordChange',
    is_temporary_password: 'isTemporaryPassword',
    last_login: 'lastLogin',
    user_id: 'userId',
    token_hash: 'tokenHash',
    ip_address: 'ipAddress',
    user_agent: 'userAgent',
    last_active_at: 'lastActiveAt',
    expires_at: 'expiresAt',
    termination_reason: 'terminationReason',
    config_key: 'configKey',
    config_value: 'configValue',
    config_type: 'configType',
    requires_reauth: 'requiresReauth',
    field_id: 'fieldId',
    default_name: 'defaultName',
    requested_at: 'requestedAt',
    processed_at: 'processedAt',
    processed_by: 'processedBy',
    user_name: 'userName',
    user_role: 'userRole',
    target_type: 'targetType',
    target_id: 'targetId',
    before_value: 'beforeValue',
    after_value: 'afterValue',
    session_id: 'sessionId',
    signature_meaning: 'signatureMeaning',
    target_user_id: 'targetUserId',
    for_user_id: 'forUserId',
    for_role: 'forRole',
    is_read: 'isRead',
    read_at: 'readAt',
    sidebar_items: 'sidebarItems',
    home_widgets: 'homeWidgets',
    permissions: 'permissions',
  };

  // Fields that must always be strings (even if they look numeric)
  const STRING_FIELDS = new Set([
    'username', 'name', 'displayName', 'fullName', 'email', 'department',
    'role', 'status', 'description', 'color', 'action',
    'createdBy', 'updatedBy', 'processedBy', 'userId', 'userName',
    'userRole', 'targetType', 'targetId', 'sessionId', 'ipAddress',
    'signatureMeaning', 'targetUserId', 'forUserId', 'forRole',
    'configKey', 'configType', 'fieldId', 'defaultName',
    'passwordHash', 'tokenHash', 'userAgent', 'terminationReason',
    'photoUrl', 'notes', 'newPassword', 'title', 'message', 'type',
    'configValue',
  ]);

  const result: Record<string, any[]> = {};
  for (const [key, rows] of Object.entries(data)) {
    if (!Array.isArray(rows)) { result[key] = rows; continue; }
    result[key] = rows.map(row => {
      const mapped: Record<string, any> = {};
      for (const [col, val] of Object.entries(row)) {
        const field = COLUMN_MAP[col] ?? col;
        // Coerce numeric values back to strings for known string fields
        if (STRING_FIELDS.has(field) && val !== null && val !== undefined && typeof val === 'number') {
          mapped[field] = String(val);
        } else {
          mapped[field] = val;
        }
      }
      return mapped;
    });
  }
  return result;
}

/** Convert DB table names to Prisma model keys */
function convertDbKeysToPrisma(data: Record<string, any[]>): Record<string, any[]> {
  const DB_TO_PRISMA: Record<string, string> = {
    'users': 'users',
    'roles': 'roles',
    'system_config': 'systemConfig',
    'audit_trail': 'auditTrail',
    'notifications': 'notifications',
    'password_history': 'passwordHistory',
    'sessions': 'sessions',
    'field_id_config': 'fieldIdConfig',
    'user_configs': 'userConfigs',
    'role_configs': 'roleConfigs',
    'password_reset_requests': 'passwordResetRequests',
  };

  const result: Record<string, any[]> = {};
  for (const [key, rows] of Object.entries(data)) {
    const prismaKey = DB_TO_PRISMA[key] ?? key;
    result[prismaKey] = rows;
  }
  // Also convert DB column names to Prisma field names
  return convertDbColumnsToPrisma(result);
}

/**
 * Parse a CSV ZIP backup into BackupData.
 */
function parseCsvZipBackup(rawBuffer: Buffer): BackupData {
  const zip = new AdmZip(rawBuffer);
  const entries = zip.getEntries();

  // Read metadata
  const metaEntry = entries.find(e => e.entryName === '_metadata.json');
  let generatedBy = 'unknown';
  let timestamp = new Date().toISOString();
  if (metaEntry) {
    try {
      const meta = JSON.parse(metaEntry.getData().toString('utf-8'));
      generatedBy = meta.generatedBy ?? 'unknown';
      timestamp = meta.timestamp ?? timestamp;
    } catch {}
  }

  const data: Record<string, any[]> = {};
  for (const entry of entries) {
    if (entry.entryName === '_metadata.json') continue;
    if (!entry.entryName.endsWith('.csv')) continue;

    const tableName = entry.entryName.replace('.csv', '');
    const csvContent = entry.getData().toString('utf-8');
    data[tableName] = parseCsvContent(csvContent);
  }

  const prismaData = convertDbKeysToPrisma(data);

  return {
    metadata: {
      version: '1.0.0',
      timestamp,
      generatedBy,
      tableCount: Object.keys(prismaData).length,
      checksum: computeBackupChecksum(prismaData),
      format: 'csv',
    },
    data: prismaData,
  };
}

function parseBackupFile(rawBuffer: Buffer): BackupData {
  // Detect ZIP (.csv backup) — ZIP magic bytes: 0x50 0x4b
  if (rawBuffer[0] === 0x50 && rawBuffer[1] === 0x4b) {
    return parseCsvZipBackup(rawBuffer);
  }

  // Detect gzip (.bak) — gzip magic bytes: 0x1f 0x8b
  let content: string;
  if (rawBuffer[0] === 0x1f && rawBuffer[1] === 0x8b) {
    try {
      content = gunzipSync(rawBuffer).toString('utf-8');
    } catch {
      throw Object.assign(new Error('Failed to decompress .bak file. File may be corrupted.'), {
        code: 'INVALID_BAK',
      });
    }
  } else {
    content = rawBuffer.toString('utf-8');
  }

  // Detect SQL format
  if (content.trimStart().startsWith('-- DigiLog Database Backup')) {
    return parseSqlBackup(content);
  }

  let backup: BackupData;
  try {
    backup = JSON.parse(content);
  } catch {
    throw Object.assign(new Error('Backup file is not valid JSON. Supported formats: .json, .bak, .sql, .zip (CSV)'), {
      code: 'INVALID_JSON',
    });
  }

  if (!backup.metadata || !backup.data) {
    throw Object.assign(new Error('Backup file is missing metadata or data sections'), {
      code: 'INVALID_BACKUP',
    });
  }

  return backup;
}

// ---------------------------------------------------------------------------
// Export: JSON format (default)
// ---------------------------------------------------------------------------

export async function exportJson(
  username: string,
  ctx: RequestContext,
): Promise<{ backup: BackupData; filename: string }> {
  const data = await fetchAllTablesPrisma();
  const checksum = computeBackupChecksum(data);
  const timestamp = new Date().toISOString();

  const backup: BackupData = {
    metadata: {
      version: '1.0.0',
      timestamp,
      generatedBy: username,
      tableCount: Object.keys(data).length,
      checksum,
      format: 'json',
    },
    data,
  };

  await auditLog({
    userId: ctx.userId,
    userRole: ctx.userRole,
    action: 'BACKUP_CREATED',
    targetType: 'system',
    targetId: 'database_backup',
    afterValue: {
      format: 'json',
      timestamp,
      checksum,
      tableCount: Object.keys(data).length,
      totalRecords: Object.values(data).reduce((sum, arr) => sum + arr.length, 0),
    },
    signatureMeaning: 'Full database backup created by administrator',
    ipAddress: ctx.ipAddress,
    userAgent: ctx.userAgent,
    sessionId: ctx.sessionId,
  });

  return { backup, filename: `digilog_backup_${dateStamp()}.json` };
}

// ---------------------------------------------------------------------------
// Export: BAK format (gzip-compressed JSON)
// ---------------------------------------------------------------------------

export async function exportBak(
  username: string,
  ctx: RequestContext,
): Promise<{ compressed: Buffer; filename: string }> {
  const data = await fetchAllTablesPrisma();
  const checksum = computeBackupChecksum(data);
  const timestamp = new Date().toISOString();

  const backup: BackupData = {
    metadata: {
      version: '1.0.0',
      timestamp,
      generatedBy: username,
      tableCount: Object.keys(data).length,
      checksum,
      format: 'bak',
    },
    data,
  };

  const jsonStr = JSON.stringify(backup);
  const compressed = gzipSync(Buffer.from(jsonStr, 'utf-8'), { level: 9 });

  await auditLog({
    userId: ctx.userId,
    userRole: ctx.userRole,
    action: 'BACKUP_CREATED',
    targetType: 'system',
    targetId: 'database_backup',
    afterValue: {
      format: 'bak',
      timestamp,
      checksum,
      tableCount: Object.keys(data).length,
      totalRecords: Object.values(data).reduce((sum, arr) => sum + arr.length, 0),
      compressedSize: compressed.length,
      originalSize: jsonStr.length,
    },
    signatureMeaning: 'Compressed database backup created by administrator',
    ipAddress: ctx.ipAddress,
    userAgent: ctx.userAgent,
    sessionId: ctx.sessionId,
  });

  return { compressed, filename: `digilog_backup_${dateStamp()}.bak` };
}

// ---------------------------------------------------------------------------
// Export: SQL format
// ---------------------------------------------------------------------------

export async function exportSql(
  username: string,
  ctx: RequestContext,
): Promise<{ sqlContent: string; filename: string }> {
  const rawData = await fetchAllTablesRaw();
  const totalRecords = Object.values(rawData).reduce((sum, arr) => sum + arr.length, 0);

  const sqlParts: string[] = [];
  sqlParts.push('-- DigiLog Database Backup');
  sqlParts.push(`-- Generated: ${new Date().toISOString()}`);
  sqlParts.push(`-- Generated By: ${username}`);
  sqlParts.push(`-- Total Records: ${totalRecords}`);
  sqlParts.push(`-- Format: PostgreSQL SQL`);
  sqlParts.push('');
  sqlParts.push('BEGIN;');
  sqlParts.push('');

  // FK-safe order: delete children first, insert parents first
  const deleteOrder = [...DB_TABLES].reverse();
  for (const table of deleteOrder) {
    sqlParts.push(`TRUNCATE TABLE "${table}" CASCADE;`);
  }
  sqlParts.push('');

  for (const table of DB_TABLES) {
    const rows = rawData[table];
    if (rows.length === 0) {
      sqlParts.push(`-- Table: ${table} (0 rows)`);
      sqlParts.push('');
      continue;
    }
    const columns = Object.keys(rows[0]);
    sqlParts.push(`-- Table: ${table} (${rows.length} rows)`);
    for (const row of rows) {
      const values = columns.map(col => escapeSqlValue(row[col]));
      sqlParts.push(
        `INSERT INTO "${table}" (${columns.map(c => `"${c}"`).join(', ')}) VALUES (${values.join(', ')});`,
      );
    }
    sqlParts.push('');
  }

  sqlParts.push('COMMIT;');

  await auditLog({
    userId: ctx.userId,
    userRole: ctx.userRole,
    action: 'BACKUP_CREATED',
    targetType: 'system',
    targetId: 'database_backup',
    afterValue: { format: 'sql', timestamp: new Date().toISOString(), totalRecords },
    signatureMeaning: 'SQL database backup created by administrator',
    ipAddress: ctx.ipAddress,
    userAgent: ctx.userAgent,
    sessionId: ctx.sessionId,
  });

  return { sqlContent: sqlParts.join('\n'), filename: `digilog_backup_${dateStamp()}.sql` };
}

// ---------------------------------------------------------------------------
// Export: CSV format (ZIP archive of per-table CSVs)
// ---------------------------------------------------------------------------

export async function exportCsv(
  username: string,
  ctx: RequestContext,
): Promise<{ zipBuffer: Buffer; filename: string }> {
  const rawData = await fetchAllTablesRaw();
  const totalRecords = Object.values(rawData).reduce((sum, arr) => sum + arr.length, 0);

  const zip = new AdmZip();

  for (const table of DB_TABLES) {
    const rows = rawData[table];
    const csvContent = generateCsv(rows);
    zip.addFile(`${table}.csv`, Buffer.from(csvContent, 'utf-8'));
  }

  // Add a metadata file
  const metaContent = JSON.stringify(
    {
      version: '1.0.0',
      timestamp: new Date().toISOString(),
      generatedBy: username,
      format: 'csv',
      tableCount: DB_TABLES.length,
      totalRecords,
      tables: Object.fromEntries(DB_TABLES.map(t => [t, rawData[t].length])),
    },
    null,
    2,
  );
  zip.addFile('_metadata.json', Buffer.from(metaContent, 'utf-8'));

  await auditLog({
    userId: ctx.userId,
    userRole: ctx.userRole,
    action: 'BACKUP_CREATED',
    targetType: 'system',
    targetId: 'database_backup',
    afterValue: { format: 'csv', timestamp: new Date().toISOString(), totalRecords },
    signatureMeaning: 'CSV database backup created by administrator',
    ipAddress: ctx.ipAddress,
    userAgent: ctx.userAgent,
    sessionId: ctx.sessionId,
  });

  return { zipBuffer: zip.toBuffer(), filename: `digilog_backup_${dateStamp()}.zip` };
}

// ---------------------------------------------------------------------------
// Restore
// ---------------------------------------------------------------------------

export async function restore(
  fileBuffer: Buffer,
  ctx: RequestContext,
): Promise<{
  success: boolean;
  message: string;
  backupTimestamp: string;
  backupVersion: string;
}> {
  const backup = parseBackupFile(fileBuffer);

  if (!backup.metadata.version) {
    throw Object.assign(new Error('Backup metadata is incomplete'), {
      code: 'INVALID_METADATA',
    });
  }

  // Checksum verification (skip for SQL/CSV since checksum is computed on import)
  const fmt = backup.metadata.format ?? 'json';
  if (fmt === 'json' || fmt === 'bak') {
    if (!backup.metadata.checksum) {
      throw Object.assign(new Error('Backup metadata is missing checksum'), {
        code: 'INVALID_METADATA',
      });
    }
    const computedChecksum = computeBackupChecksum(backup.data);
    if (computedChecksum !== backup.metadata.checksum) {
      throw Object.assign(new Error(
        'Backup file integrity check failed. The file may have been tampered with or corrupted.',
      ), { code: 'CHECKSUM_MISMATCH' });
    }
  }

  await restoreFromBackup(backup);

  // Audit log the restore
  await auditLog({
    userId: ctx.userId,
    userRole: ctx.userRole,
    action: 'BACKUP_RESTORED',
    targetType: 'system',
    targetId: 'database_restore',
    afterValue: {
      backupTimestamp: backup.metadata.timestamp,
      backupVersion: backup.metadata.version,
      backupChecksum: backup.metadata.checksum,
      generatedBy: backup.metadata.generatedBy,
    },
    signatureMeaning: 'Database restored from backup by administrator',
    ipAddress: ctx.ipAddress,
    userAgent: ctx.userAgent,
    sessionId: ctx.sessionId,
  });

  return {
    success: true,
    message: 'Database restored successfully',
    backupTimestamp: backup.metadata.timestamp,
    backupVersion: backup.metadata.version,
  };
}

// ---------------------------------------------------------------------------
// Validate (no DB mutation)
// ---------------------------------------------------------------------------

export async function validate(
  fileBuffer: Buffer,
): Promise<{
  valid: boolean;
  metadata: BackupData['metadata'];
  tableSummary: Record<string, number>;
  checksumValid: boolean;
  totalRecords: number;
}> {
  const backup = parseBackupFile(fileBuffer);

  const computedChecksum = computeBackupChecksum(backup.data);
  const checksumValid = computedChecksum === backup.metadata.checksum;

  const tableSummary: Record<string, number> = {};
  for (const [key, value] of Object.entries(backup.data)) {
    if (Array.isArray(value)) tableSummary[key] = value.length;
  }

  return {
    valid: checksumValid,
    metadata: backup.metadata,
    tableSummary,
    checksumValid,
    totalRecords: Object.values(tableSummary).reduce((s, n) => s + n, 0),
  };
}
