export const AUDIT_ACTIONS = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_ENABLED: 'USER_ENABLED',
  USER_DISABLED: 'USER_DISABLED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  SESSION_TIMEOUT: 'SESSION_TIMEOUT',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  PASSWORD_EXPIRED: 'PASSWORD_EXPIRED',
  CONFIG_CHANGED: 'CONFIG_CHANGED',
  APPROVAL_REQUESTED: 'APPROVAL_REQUESTED',
  APPROVAL_GRANTED: 'APPROVAL_GRANTED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  DATA_VIEWED: 'DATA_VIEWED',
  DATA_EXPORTED: 'DATA_EXPORTED',
  UNAUTHORIZED_ACTION_ATTEMPT: 'UNAUTHORIZED_ACTION_ATTEMPT',
  BULK_USER_DELETED: 'BULK_USER_DELETED',
  BACKUP_CREATED: 'BACKUP_CREATED',
  BACKUP_RESTORED: 'BACKUP_RESTORED',

  // Entity Management
  ASSET_TEMPLATE_CREATED: 'ASSET_TEMPLATE_CREATED',
  ASSET_TEMPLATE_UPDATED: 'ASSET_TEMPLATE_UPDATED',
  ASSET_TEMPLATE_DELETED: 'ASSET_TEMPLATE_DELETED',
  ASSET_TEMPLATE_VERSION_CREATED: 'ASSET_TEMPLATE_VERSION_CREATED',
  ASSET_CREATED: 'ASSET_CREATED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_STATUS_CHANGED: 'ASSET_STATUS_CHANGED',
  ASSET_DELETED: 'ASSET_DELETED',
  ASSET_RELATIONSHIP_CREATED: 'ASSET_RELATIONSHIP_CREATED',
  ASSET_RELATIONSHIP_DELETED: 'ASSET_RELATIONSHIP_DELETED',
  ASSET_IDENTIFIER_CREATED: 'ASSET_IDENTIFIER_CREATED',
  ASSET_IDENTIFIER_DELETED: 'ASSET_IDENTIFIER_DELETED',

  // Data Ingestion & Integration (Phase A)
  DATA_ATTRIBUTES_UPDATED: 'DATA_ATTRIBUTES_UPDATED',
  DATA_CHECKLIST_SUBMITTED: 'DATA_CHECKLIST_SUBMITTED',

  // Alarms
  ALARM_CREATED: 'ALARM_CREATED',
  ALARM_ACKNOWLEDGED: 'ALARM_ACKNOWLEDGED',
  ALARM_CLEARED: 'ALARM_CLEARED',
  ALARM_ESCALATED: 'ALARM_ESCALATED',

  // Checklist workflow
  CHECKLIST_REVIEWED: 'CHECKLIST_REVIEWED',
  CHECKLIST_APPROVED: 'CHECKLIST_APPROVED',
  CHECKLIST_REJECTED: 'CHECKLIST_REJECTED',
  CHECKLIST_REOPENED: 'CHECKLIST_REOPENED',
  SEPARATION_OF_DUTIES_DISABLED: 'SEPARATION_OF_DUTIES_DISABLED',

  // Rule chain
  RULE_CHAIN_CREATED: 'RULE_CHAIN_CREATED',
  RULE_CHAIN_UPDATED: 'RULE_CHAIN_UPDATED',
  RULE_CHAIN_DELETED: 'RULE_CHAIN_DELETED',
  RULE_CHAIN_SET_ROOT: 'RULE_CHAIN_SET_ROOT',
  RULE_CHAIN_IMPORTED: 'RULE_CHAIN_IMPORTED',

  // Credentials
  DEVICE_CREDENTIAL_REGENERATED: 'DEVICE_CREDENTIAL_REGENERATED',

  // UNS
  UNS_PATH_OVERRIDDEN: 'UNS_PATH_OVERRIDDEN',
  UNS_CONFIG_UPDATED: 'UNS_CONFIG_UPDATED',

  // Help
  HELP_ARTICLE_CREATED: 'HELP_ARTICLE_CREATED',
  HELP_ARTICLE_UPDATED: 'HELP_ARTICLE_UPDATED',
  HELP_ARTICLE_DELETED: 'HELP_ARTICLE_DELETED',

  // Retention
  RETENTION_POLICY_UPDATED: 'RETENTION_POLICY_UPDATED',
  DATA_ARCHIVED: 'DATA_ARCHIVED',
  RETENTION_EXECUTED: 'RETENTION_EXECUTED',

  // System Config
  SYSTEM_CONFIG_UPDATED: 'SYSTEM_CONFIG_UPDATED',
  SERVER_RESTART_TRIGGERED: 'SERVER_RESTART_TRIGGERED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
