export const PERMISSIONS = {

  // User management
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ENABLE_DISABLE: 'USER_ENABLE_DISABLE',
  USER_UNLOCK: 'USER_UNLOCK',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',

  // Configuration
  CONFIG_READ: 'CONFIG_READ',
  CONFIG_UPDATE: 'CONFIG_UPDATE',
  FIELD_ID_UPDATE: 'FIELD_ID_UPDATE',
  ROLE_MANAGE: 'ROLE_MANAGE',

  // Audit
  AUDIT_READ: 'AUDIT_READ',
  AUDIT_EXPORT: 'AUDIT_EXPORT',

  // Filter Events
  EVENT_READ: 'EVENT_READ',

  // Notifications
  NOTIFICATION_VIEW: 'NOTIFICATION_VIEW',
  NOTIFICATION_CREATE: 'NOTIFICATION_CREATE',
  NOTIFICATION_UPDATE: 'NOTIFICATION_UPDATE',
  NOTIFICATION_DELETE: 'NOTIFICATION_DELETE',
  NOTIFICATION_MANAGE: 'NOTIFICATION_MANAGE',

  // Asset Management
  ASSET_READ: 'ASSET_READ',
  ASSET_VIEW: 'ASSET_VIEW',
  ASSET_CREATE: 'ASSET_CREATE',
  ASSET_UPDATE: 'ASSET_UPDATE',
  ASSET_DELETE: 'ASSET_DELETE',

  // Asset Templates
  ASSET_TEMPLATE_CREATE: 'ASSET_TEMPLATE_CREATE',
  ASSET_TEMPLATE_UPDATE: 'ASSET_TEMPLATE_UPDATE',
  ASSET_TEMPLATE_DELETE: 'ASSET_TEMPLATE_DELETE',

  // Asset Relationships
  ASSET_RELATIONSHIP_CREATE: 'ASSET_RELATIONSHIP_CREATE',
  ASSET_RELATIONSHIP_DELETE: 'ASSET_RELATIONSHIP_DELETE',

  // Asset Identifiers
  ASSET_IDENTIFIER_CREATE: 'ASSET_IDENTIFIER_CREATE',
  ASSET_IDENTIFIER_DELETE: 'ASSET_IDENTIFIER_DELETE',

  // Entity Assignment
  ENTITY_ASSIGN: 'ENTITY_ASSIGN',

  // Dashboard
  DASHBOARD_CREATE: 'DASHBOARD_CREATE',
  DASHBOARD_MANAGE: 'DASHBOARD_MANAGE',
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  DASHBOARD_ASSIGN: 'DASHBOARD_ASSIGN',

  // Rule Chain
  RULE_CHAIN_VIEW: 'RULE_CHAIN_VIEW',
  RULE_CHAIN_CREATE: 'RULE_CHAIN_CREATE',
  RULE_CHAIN_UPDATE: 'RULE_CHAIN_UPDATE',
  RULE_CHAIN_DELETE: 'RULE_CHAIN_DELETE',

  // Alarm
  ALARM_VIEW: 'ALARM_VIEW',
  ALARM_ACKNOWLEDGE: 'ALARM_ACKNOWLEDGE',
  ALARM_CLEAR: 'ALARM_CLEAR',

  // UNS
  UNS_VIEW: 'UNS_VIEW',
  UNS_MANAGE: 'UNS_MANAGE',

  // Checklist
  CHECKLIST_SUBMIT: 'CHECKLIST_SUBMIT',

  // Debug Trace
  READ_DEBUG_TRACE: 'READ_DEBUG_TRACE',
  MANAGE_DEBUG_TRACE: 'MANAGE_DEBUG_TRACE',

  // Filter Operations (Phase 2)
  FILTER_OPERATE: 'FILTER_OPERATE',
  FILTER_BYPASS: 'FILTER_BYPASS',

  // Filter List Page Controls (visibility toggles)
  FILTER_BULK_UPLOAD: 'FILTER_BULK_UPLOAD',
  FILTER_CREATE: 'FILTER_CREATE',
  FILTER_EDIT: 'FILTER_EDIT',
  FILTER_DELETE: 'FILTER_DELETE',
  FILTER_RETIRE: 'FILTER_RETIRE',
  FILTER_REPLACE: 'FILTER_REPLACE',
  FILTER_STATUS_UPDATE: 'FILTER_STATUS_UPDATE',
  FILTER_HIERARCHY_CREATE: 'FILTER_HIERARCHY_CREATE',
  FILTER_HIERARCHY_EDIT: 'FILTER_HIERARCHY_EDIT',
  FILTER_HIERARCHY_DELETE: 'FILTER_HIERARCHY_DELETE',
  FILTER_RFID_MANAGE: 'FILTER_RFID_MANAGE',

  // Filter Cleaning Profiles (Phase 2)
  FCP_READ: 'FCP_READ',
  FCP_CREATE: 'FCP_CREATE',
  FCP_UPDATE: 'FCP_UPDATE',
  FCP_DELETE: 'FCP_DELETE',

  // Checklist Page Controls
  CHECKLIST_CREATE: 'CHECKLIST_CREATE',
  CHECKLIST_EDIT: 'CHECKLIST_EDIT',
  CHECKLIST_DELETE: 'CHECKLIST_DELETE',
  CHECKLIST_TOGGLE: 'CHECKLIST_TOGGLE',

  // Cleaning Profile Page Controls
  CP_TOGGLE: 'CP_TOGGLE',
  CP_PAGE_CREATE: 'CP_PAGE_CREATE',
  CP_PAGE_EDIT: 'CP_PAGE_EDIT',
  CP_PAGE_DELETE: 'CP_PAGE_DELETE',

  // Equipment Group Page Controls
  EG_VIEW: 'EG_VIEW',
  EG_CREATE: 'EG_CREATE',
  EG_EDIT: 'EG_EDIT',
  EG_DELETE: 'EG_DELETE',

  // Filter Profiles (Phase 2)
  FP_READ: 'FP_READ',
  FP_CREATE: 'FP_CREATE',
  FP_UPDATE: 'FP_UPDATE',
  FP_DELETE: 'FP_DELETE',
  FP_ASSIGN: 'FP_ASSIGN',

  // PM Schedules (Phase 2)
  PM_READ: 'PM_READ',
  PM_CREATE: 'PM_CREATE',
  PM_UPDATE: 'PM_UPDATE',
  PM_DELETE: 'PM_DELETE',
  PM_EXECUTE: 'PM_EXECUTE',
  PM_APPROVE: 'PM_APPROVE',

  // PM Page Controls
  PM_DOWNLOAD_TEMPLATE: 'PM_DOWNLOAD_TEMPLATE',
  PM_UPLOAD: 'PM_UPLOAD',
  PM_EDIT_ENTRY: 'PM_EDIT_ENTRY',
  PM_RESUBMIT: 'PM_RESUBMIT',

  // Cleaning Cycles (Phase 2)
  CYCLE_READ: 'CYCLE_READ',

  // Backup
  BACKUP_MANAGE: 'BACKUP_MANAGE',

  // Block Change Requests
  BLOCK_CHANGE_REQUEST: 'BLOCK_CHANGE_REQUEST',
  BLOCK_CHANGE_APPROVE: 'BLOCK_CHANGE_APPROVE',

  // Report Templates
  REPORT_TEMPLATE_READ: 'REPORT_TEMPLATE_READ',
  REPORT_TEMPLATE_CREATE: 'REPORT_TEMPLATE_CREATE',
  REPORT_TEMPLATE_UPDATE: 'REPORT_TEMPLATE_UPDATE',
  REPORT_TEMPLATE_DELETE: 'REPORT_TEMPLATE_DELETE',

  // Report Instances
  REPORT_GENERATE: 'REPORT_GENERATE',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_SIGN: 'REPORT_SIGN',
  REPORT_DELETE: 'REPORT_DELETE',
  REPORT_EXPORT: 'REPORT_EXPORT',

  // Version History (2026-05-02): cross-entity audit-history viewer for the
  // four versioned entities (CleaningProfile lineage, FilterProfile sidecar,
  // ChecklistProfile sidecar, EquipmentGroup composite sidecar). SUPER_ADMIN
  // only by default; assignable to other roles via Role Privileges config.
  // The four `/api/<entity>/:id/versions` route gates also accept this perm
  // (in addition to the entity-specific read perms) so a user granted ONLY
  // VERSION_HISTORY_VIEW can browse history without entity edit rights.
  VERSION_HISTORY_VIEW: 'VERSION_HISTORY_VIEW',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
