import { type Role, ROLES } from './roles.js';

export const PERMISSIONS = {
  // User management
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ENABLE_DISABLE: 'USER_ENABLE_DISABLE',
  USER_UNLOCK: 'USER_UNLOCK',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',

  // Configuration
  CONFIG_READ: 'CONFIG_READ',
  CONFIG_UPDATE: 'CONFIG_UPDATE',
  FIELD_ID_UPDATE: 'FIELD_ID_UPDATE',

  // Asset hierarchy
  NODE_CREATE: 'NODE_CREATE',
  NODE_READ: 'NODE_READ',
  NODE_UPDATE: 'NODE_UPDATE',
  NODE_DELETE: 'NODE_DELETE',

  // Templates
  TEMPLATE_CREATE: 'TEMPLATE_CREATE',
  TEMPLATE_READ: 'TEMPLATE_READ',
  TEMPLATE_UPDATE: 'TEMPLATE_UPDATE',
  TEMPLATE_DELETE: 'TEMPLATE_DELETE',

  // Audit
  AUDIT_READ: 'AUDIT_READ',

  // Approvals
  APPROVAL_REVIEW: 'APPROVAL_REVIEW',
  APPROVAL_REQUEST: 'APPROVAL_REQUEST',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.USER_CREATE, PERMISSIONS.USER_READ, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE, PERMISSIONS.USER_ENABLE_DISABLE, PERMISSIONS.USER_UNLOCK,
    PERMISSIONS.USER_RESET_PASSWORD,
    PERMISSIONS.CONFIG_READ, PERMISSIONS.CONFIG_UPDATE,
    PERMISSIONS.NODE_READ,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.SUPERVISOR]: [
    PERMISSIONS.NODE_READ,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.APPROVAL_REVIEW,
  ],
  [ROLES.MAINTENANCE]: [
    PERMISSIONS.NODE_CREATE, PERMISSIONS.NODE_READ, PERMISSIONS.NODE_UPDATE, PERMISSIONS.NODE_DELETE,
    PERMISSIONS.TEMPLATE_CREATE, PERMISSIONS.TEMPLATE_READ, PERMISSIONS.TEMPLATE_UPDATE, PERMISSIONS.TEMPLATE_DELETE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.APPROVAL_REQUEST,
  ],
  [ROLES.OPERATOR]: [
    PERMISSIONS.NODE_READ,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.NODE_READ,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.AUDIT_READ,
  ],
};
