import { ROLES } from './roles.js';

export const PERMISSIONS = {
  // User management
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ENABLE_DISABLE: 'USER_ENABLE_DISABLE',
  USER_UNLOCK: 'USER_UNLOCK',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',

  // Configuration
  CONFIG_READ: 'CONFIG_READ',
  CONFIG_UPDATE: 'CONFIG_UPDATE',
  FIELD_ID_UPDATE: 'FIELD_ID_UPDATE',
  ROLE_MANAGE: 'ROLE_MANAGE',

  // Audit
  AUDIT_READ: 'AUDIT_READ',

  // Approvals
  APPROVAL_REVIEW: 'APPROVAL_REVIEW',
  APPROVAL_REQUEST: 'APPROVAL_REQUEST',

  // Asset Management
  ASSET_TEMPLATE_MANAGE: 'ASSET_TEMPLATE_MANAGE',
  ASSET_CREATE: 'ASSET_CREATE',
  ASSET_UPDATE: 'ASSET_UPDATE',
  ASSET_DELETE: 'ASSET_DELETE',
  ASSET_RELATIONSHIP_MANAGE: 'ASSET_RELATIONSHIP_MANAGE',
  ASSET_IDENTIFIER_MANAGE: 'ASSET_IDENTIFIER_MANAGE',
  ASSET_VIEW: 'ASSET_VIEW',
  TEMPLATE_LINKING_RULE_MANAGE: 'TEMPLATE_LINKING_RULE_MANAGE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * @deprecated Role permissions are now stored in the database and fetched dynamically
 * This is kept for backward compatibility during migration
 */
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.USER_CREATE, PERMISSIONS.USER_READ, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE, PERMISSIONS.USER_ENABLE_DISABLE, PERMISSIONS.USER_UNLOCK,
    PERMISSIONS.USER_RESET_PASSWORD,
    PERMISSIONS.CONFIG_READ, PERMISSIONS.CONFIG_UPDATE,
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.SUPERVISOR]: [
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.APPROVAL_REVIEW,
  ],
  [ROLES.MAINTENANCE]: [
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.APPROVAL_REQUEST,
  ],
  [ROLES.OPERATOR]: [
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.AUDIT_READ,
  ],
};
