import type { ModuleConfigDefinition } from '../../../lib/config-registry.js';

export const offlineSyncDef: ModuleConfigDefinition = {
  moduleKey: 'offline-sync',
  moduleName: 'Offline Sync Settings',
  description: 'Configure offline operation queue, sync behavior, and data caching for mobile tablets',
  icon: 'cloud-off',
  category: 'mobile',
  sortOrder: 31,
  permissions: { read: 'CONFIG_READ', write: 'CONFIG_UPDATE' },
  requiredRole: 'ADMIN',
  requiresReauth: false,
  hasCustomPage: false,
  settings: [
    {
      key: 'enabled',
      type: 'boolean',
      label: 'Enable Offline Mode',
      default: true,
      group: 'General',
    },
    {
      key: 'cacheTtlMinutes',
      type: 'number',
      label: 'Data Cache TTL (minutes)',
      default: 30,
      group: 'General',
    },
    {
      key: 'syncDelaySeconds',
      type: 'number',
      label: 'Sync Delay on Reconnect (seconds)',
      default: 2,
      group: 'Sync',
    },
    {
      key: 'maxRetries',
      type: 'number',
      label: 'Max Retries Per Operation',
      default: 2,
      group: 'Sync',
    },
    {
      key: 'conflictResolution',
      type: 'string',
      label: 'Conflict Resolution (SKIP | OVERWRITE | PROMPT)',
      default: 'SKIP',
      group: 'Sync',
    },
    {
      key: 'cacheFilters',
      type: 'boolean',
      label: 'Cache Filters',
      default: true,
      group: 'Cached Data',
    },
    {
      key: 'cacheTemplates',
      type: 'boolean',
      label: 'Cache Templates',
      default: true,
      group: 'Cached Data',
    },
    {
      key: 'cacheReasons',
      type: 'boolean',
      label: 'Cache Cleaning Reasons',
      default: true,
      group: 'Cached Data',
    },
    {
      key: 'cacheIdentifiers',
      type: 'boolean',
      label: 'Cache Identifiers (for offline RFID lookup)',
      default: true,
      group: 'Cached Data',
    },
  ],
};
