import type { ModuleConfigDefinition } from '../../../lib/config-registry.js';

export const pmScheduleApprovalDef: ModuleConfigDefinition = {
  moduleKey: 'pm-schedule-approval',
  moduleName: 'PM Schedule Workflow',
  description: 'Configure the upload → review → approve workflow for PM schedules: which role performs each step. Super Admin can always perform any step.',
  icon: 'clipboard-check',
  category: 'filter-management',
  sortOrder: 61,
  permissions: { read: 'CONFIG_READ', write: 'CONFIG_UPDATE' },
  requiredRole: 'SUPER_ADMIN',
  requiresReauth: false,
  hasCustomPage: false,
  settings: [
    {
      key: 'workflowEnabled',
      type: 'boolean',
      label: 'Enable Review + Approval Workflow',
      description: 'When ON, an uploaded PM schedule must be reviewed and then approved before it generates tasks. When OFF, uploads behave as before (single approval step). Turn ON only after the review screens are available.',
      group: 'Workflow',
      default: false,
    },
    {
      key: 'uploadRole',
      type: 'select',
      label: 'Upload Role',
      description: 'Role allowed to upload PM schedules. Leave blank to allow anyone with the PM upload permission. Super Admin can always upload.',
      group: 'Workflow',
      default: '',
      dynamicOptionsSource: '/api/roles/active',
      options: [],
    },
    {
      key: 'reviewRole',
      type: 'select',
      label: 'Review Role',
      description: 'Role allowed to review an uploaded schedule (modify or reject before approval). Super Admin can always review.',
      group: 'Workflow',
      default: '',
      dynamicOptionsSource: '/api/roles/active',
      options: [],
    },
    {
      key: 'approvalRole',
      type: 'select',
      label: 'Approval Role',
      description: 'Role allowed to approve (or reject) a reviewed schedule. Only approved schedules generate tasks. Super Admin can always approve.',
      group: 'Workflow',
      default: 'ADMIN',
      dynamicOptionsSource: '/api/roles/active',
      options: [],
    },
  ],
};
