import { type FastifyInstance } from 'fastify';
import { getAhuCompletionMode } from '../../filter-operations/ahu-completion-gate.js';

/**
 * AHU Cleaning Completion Process — runtime public-read endpoint.
 *
 * GET /ahu-completion-process/current — readable by any authenticated user.
 * The filter-operations advance handler reads this on every final-stage
 * submission so no admin gate is appropriate.
 *
 * The generic GET/PUT admin routes for this config are generated by
 * dynamic-routes.ts (hasCustomPage: false, requiredRole: SUPER_ADMIN).
 */
export async function ahuCompletionProcessRoutes(app: FastifyInstance) {
  app.get('/ahu-completion-process/current', {
    schema: {
      tags: ['Config'],
      summary: 'Get current AHU Cleaning Completion Process mode (public)',
      description: 'Returns the active completion enforcement mode. Available to all authenticated users.',
      response: {
        200: {
          type: 'object',
          properties: {
            mode: { type: 'string', enum: ['NONE', 'POPUP', 'INTERLOCK'] },
          },
        },
      },
    },
  }, async () => {
    const mode = await getAhuCompletionMode();
    return { mode };
  });
}
