import { type FastifyInstance } from 'fastify';
import { blockChangeService } from '../../block-change-requests/block-change.service.js';

/**
 * Cross-Block Cleaning — runtime public-read endpoint.
 *
 * GET /block-change-approval/current — readable by any authenticated user.
 * Every operator surface (tablet + desktop filter-operations) has to know the
 * mode to pick its cross-block flow, so no admin gate is appropriate. Before
 * this route existed both surfaces read the SUPER_ADMIN-gated dynamic route,
 * 403'd for every other role, and silently defaulted to 'CONFIRM' — showing a
 * confirm dialog under mode NONE, and self-confirm-then-server-reject under
 * APPROVAL.
 *
 * Only `mode` is exposed: it is all the client picks a flow from. The admin
 * fields (approvalRole, requireReason, autoExpireHours) stay behind the
 * SUPER_ADMIN gate on the generic GET/PUT routes generated by dynamic-routes.ts
 * (hasCustomPage: false, requiredRole: SUPER_ADMIN).
 */
export async function blockChangeApprovalRoutes(app: FastifyInstance) {
  app.get('/block-change-approval/current', {
    schema: {
      tags: ['Config'],
      summary: 'Get current Cross-Block Cleaning mode (public)',
      description: 'Returns the active cross-block enforcement mode. Available to all authenticated users.',
      response: {
        200: {
          type: 'object',
          properties: {
            mode: { type: 'string', enum: ['NONE', 'CONFIRM', 'APPROVAL'] },
          },
        },
      },
    },
  }, async () => {
    const mode = await blockChangeService.getMode();
    return { mode };
  });
}
