import { useState } from 'react';
import { Search, Copy, Check } from 'lucide-react';
import type { EntitySlot } from './template-types';

interface Props {
  entitySlots: EntitySlot[];
}

interface TagItem {
  tag: string;
  description: string;
}

interface TagCategory {
  label: string;
  items: TagItem[];
}

function buildCategories(entitySlots: EntitySlot[]): TagCategory[] {
  const categories: TagCategory[] = [];

  if (entitySlots.length > 0) {
    categories.push({
      label: 'Entity Attributes',
      items: entitySlots.flatMap(slot => [
        { tag: `{{attr.$${slot.name}.<field>}}`, description: `Attribute from ${slot.label || slot.name}` },
        { tag: `{{attr.$${slot.name}.*}}`, description: `All attributes of ${slot.label || slot.name}` },
      ]),
    });
    categories.push({
      label: 'Telemetry',
      items: entitySlots.flatMap(slot => [
        { tag: `{{ts.$${slot.name}.<key>[last]}}`, description: `Latest value` },
        { tag: `{{ts.$${slot.name}.<key>[avg:24h]}}`, description: `24h average` },
        { tag: `{{ts.$${slot.name}.<key>[range]}}`, description: `Full series (tables/charts)` },
      ]),
    });
    categories.push({
      label: 'Identifiers',
      items: entitySlots.map(slot => ({
        tag: `{{ident.$${slot.name}.<type>}}`,
        description: `Identifier of ${slot.label || slot.name}`,
      })),
    });
  }

  categories.push({
    label: 'Timestamps',
    items: [
      { tag: '{{time.now}}', description: 'Current time' },
      { tag: '{{time.range.start}}', description: 'Report range start' },
      { tag: '{{time.range.end}}', description: 'Report range end' },
    ],
  });

  categories.push({
    label: 'Metadata',
    items: [
      { tag: '{{meta.report.name}}', description: 'Report name' },
      { tag: '{{meta.user.name}}', description: 'Generated by' },
      { tag: '{{meta.org.name}}', description: 'Organization name' },
      { tag: '{{meta.template.name}}', description: 'Template name' },
    ],
  });

  categories.push({
    label: 'Page',
    items: [
      { tag: '{{page.current}}', description: 'Current page number' },
      { tag: '{{page.total}}', description: 'Total pages' },
    ],
  });

  return categories;
}

export function VariableTagPicker({ entitySlots }: Props) {
  const [search, setSearch] = useState('');
  const [copiedTag, setCopiedTag] = useState<string | null>(null);

  const categories = buildCategories(entitySlots);

  const filtered = search
    ? categories.map(cat => ({
        ...cat,
        items: cat.items.filter(i =>
          i.tag.toLowerCase().includes(search.toLowerCase()) ||
          i.description.toLowerCase().includes(search.toLowerCase())
        ),
      })).filter(cat => cat.items.length > 0)
    : categories;

  const copyTag = (tag: string) => {
    navigator.clipboard.writeText(tag);
    setCopiedTag(tag);
    setTimeout(() => setCopiedTag(null), 1500);
  };

  return (
    <div className="p-4">
      <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3">Variable Tags</h3>

      <div className="relative mb-3">
        <Search className="absolute left-2 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
        <input value={search} onChange={e => setSearch(e.target.value)}
          className="w-full border border-slate-200 rounded-lg pl-7 pr-3 py-1.5 text-xs outline-none"
          placeholder="Search tags..." />
      </div>

      <div className="space-y-3 max-h-80 overflow-y-auto">
        {filtered.map(cat => (
          <div key={cat.label}>
            <div className="text-xs font-semibold text-slate-400 mb-1">{cat.label}</div>
            <div className="space-y-0.5">
              {cat.items.map(item => (
                <button key={item.tag} onClick={() => copyTag(item.tag)}
                  className="w-full flex items-center gap-2 px-2 py-1.5 rounded-lg text-left hover:bg-slate-50 transition-colors group">
                  <div className="flex-1 min-w-0">
                    <div className="text-xs font-mono text-blue-600 truncate">{item.tag}</div>
                    <div className="text-xs text-slate-400 truncate">{item.description}</div>
                  </div>
                  <span className="shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                    {copiedTag === item.tag ? <Check className="w-3 h-3 text-emerald-500" /> : <Copy className="w-3 h-3 text-slate-400" />}
                  </span>
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>

      {entitySlots.length === 0 && (
        <p className="text-xs text-amber-500 mt-2">Add entity slots above to see entity-specific tags</p>
      )}
    </div>
  );
}
